name: Deploying NodeJS CRUD APP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh 
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/ssh_key ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            cd /home/ubuntu/CrudOps/backend
            git pull origin main
            npm install
            npm run build
            pm2 restart all
            cd ../..

            cd /home/ubuntu/CrudOps/frontend/web
            git pull origin main
            npm install 
            npm run build
            pm2 restart all
          EOF